/*
 * Copyright (c) 2004, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.readwritesplitting;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Statement wrapper that routes SQL execution to the appropriate connection
 * (master or replica) based on SQL type and transaction state.
 */
public class ReadWriteSplittingStatement implements Statement {

  private final PgConnectionManager connectionManager;
  private final SqlRouteEngine routeEngine;
  private final ReadWriteSplittingConnection parentConnection;

  // Delegate statement (created lazily when SQL is executed)
  private Statement delegateStatement;

  /**
   * Creates a new read-write splitting statement.
   *
   * @param connectionManager the connection manager
   * @param routeEngine the SQL route engine
   * @param parentConnection the parent connection
   */
  public ReadWriteSplittingStatement(
      PgConnectionManager connectionManager,
      SqlRouteEngine routeEngine,
      ReadWriteSplittingConnection parentConnection) {
    this.connectionManager = connectionManager;
    this.routeEngine = routeEngine;
    this.parentConnection = parentConnection;
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.executeQuery(sql);
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.executeUpdate(sql);
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.execute(sql);
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.executeUpdate(sql, autoGeneratedKeys);
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.executeUpdate(sql, columnIndexes);
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.executeUpdate(sql, columnNames);
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.execute(sql, autoGeneratedKeys);
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.execute(sql, columnIndexes);
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    Statement stmt = getRoutedStatement(sql);
    return stmt.execute(sql, columnNames);
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    // Batch operations always go to master for consistency
    Statement stmt = getMasterStatement();
    stmt.addBatch(sql);
  }

  @Override
  public int[] executeBatch() throws SQLException {
    if (delegateStatement == null) {
      throw new SQLException("No batch to execute");
    }
    return delegateStatement.executeBatch();
  }

  @Override
  public void clearBatch() throws SQLException {
    if (delegateStatement != null) {
      delegateStatement.clearBatch();
    }
  }

  /**
   * Gets the appropriate statement based on SQL routing.
   *
   * @param sql the SQL to route
   * @return the routed statement
   * @throws SQLException if routing or statement creation fails
   */
  private Statement getRoutedStatement(String sql) throws SQLException {
    RouteTarget target = routeEngine.route(
        sql,
        parentConnection.getAutoCommit(),
        parentConnection.getTargetServerType());

    Connection conn;
    if (target == RouteTarget.MASTER) {
      conn = connectionManager.getMasterConnection();
    } else {
      conn = connectionManager.getReplicaConnection();
    }

    // Create a new statement on the routed connection
    delegateStatement = conn.createStatement();

    // Apply statement settings
    if (fetchSize != -1) {
      delegateStatement.setFetchSize(fetchSize);
    }
    if (maxRows != -1) {
      delegateStatement.setMaxRows(maxRows);
    }
    if (maxFieldSize != -1) {
      delegateStatement.setMaxFieldSize(maxFieldSize);
    }
    if (queryTimeout != -1) {
      delegateStatement.setQueryTimeout(queryTimeout);
    }
    if (fetchDirection != -1) {
      delegateStatement.setFetchDirection(fetchDirection);
    }
    if (escapeProcessing != null) {
      delegateStatement.setEscapeProcessing(escapeProcessing);
    }
    if (cursorName != null) {
      delegateStatement.setCursorName(cursorName);
    }

    return delegateStatement;
  }

  /**
   * Gets a statement on the master connection.
   *
   * @return statement on master
   * @throws SQLException if statement creation fails
   */
  private Statement getMasterStatement() throws SQLException {
    Connection conn = connectionManager.getMasterConnection();
    delegateStatement = conn.createStatement();
    return delegateStatement;
  }

  // Statement settings (recorded for replay on delegate)
  private int fetchSize = -1;
  private int maxRows = -1;
  private int maxFieldSize = -1;
  private int queryTimeout = -1;
  private int fetchDirection = -1;
  private Boolean escapeProcessing = null;
  private String cursorName = null;

  @Override
  public void setFetchSize(int rows) throws SQLException {
    this.fetchSize = rows;
    if (delegateStatement != null) {
      delegateStatement.setFetchSize(rows);
    }
  }

  @Override
  public int getFetchSize() throws SQLException {
    return fetchSize != -1 ? fetchSize : 0;
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    this.maxRows = max;
    if (delegateStatement != null) {
      delegateStatement.setMaxRows(max);
    }
  }

  @Override
  public int getMaxRows() throws SQLException {
    return maxRows != -1 ? maxRows : 0;
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    this.maxFieldSize = max;
    if (delegateStatement != null) {
      delegateStatement.setMaxFieldSize(max);
    }
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    return maxFieldSize != -1 ? maxFieldSize : 0;
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    this.queryTimeout = seconds;
    if (delegateStatement != null) {
      delegateStatement.setQueryTimeout(seconds);
    }
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    return queryTimeout != -1 ? queryTimeout : 0;
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    this.fetchDirection = direction;
    if (delegateStatement != null) {
      delegateStatement.setFetchDirection(direction);
    }
  }

  @Override
  public int getFetchDirection() throws SQLException {
    return fetchDirection != -1 ? fetchDirection : ResultSet.FETCH_FORWARD;
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    this.escapeProcessing = enable;
    if (delegateStatement != null) {
      delegateStatement.setEscapeProcessing(enable);
    }
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    this.cursorName = name;
    if (delegateStatement != null) {
      delegateStatement.setCursorName(name);
    }
  }

  // Delegate methods
  @Override
  public void close() throws SQLException {
    if (delegateStatement != null) {
      delegateStatement.close();
    }
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    return delegateStatement != null ? delegateStatement.getResultSet() : null;
  }

  @Override
  public int getUpdateCount() throws SQLException {
    return delegateStatement != null ? delegateStatement.getUpdateCount() : -1;
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    return delegateStatement != null && delegateStatement.getMoreResults();
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    return delegateStatement != null && delegateStatement.getMoreResults(current);
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return delegateStatement != null ? delegateStatement.getWarnings() : null;
  }

  @Override
  public void clearWarnings() throws SQLException {
    if (delegateStatement != null) {
      delegateStatement.clearWarnings();
    }
  }

  @Override
  public void cancel() throws SQLException {
    if (delegateStatement != null) {
      delegateStatement.cancel();
    }
  }

  @Override
  public Connection getConnection() throws SQLException {
    return parentConnection;
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    return delegateStatement != null ? delegateStatement.getGeneratedKeys() : null;
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    return ResultSet.CONCUR_READ_ONLY;
  }

  @Override
  public int getResultSetType() throws SQLException {
    return ResultSet.TYPE_FORWARD_ONLY;
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    return ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  @Override
  public boolean isClosed() throws SQLException {
    return delegateStatement != null && delegateStatement.isClosed();
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    if (delegateStatement != null) {
      delegateStatement.setPoolable(poolable);
    }
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return delegateStatement != null && delegateStatement.isPoolable();
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    if (delegateStatement != null) {
      delegateStatement.closeOnCompletion();
    }
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    return delegateStatement != null && delegateStatement.isCloseOnCompletion();
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isAssignableFrom(getClass())) {
      return iface.cast(this);
    }
    if (delegateStatement != null) {
      return delegateStatement.unwrap(iface);
    }
    throw new SQLException("Cannot unwrap to " + iface.getName());
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return iface.isAssignableFrom(getClass())
        || (delegateStatement != null && delegateStatement.isWrapperFor(iface));
  }
}
