/*
 * Copyright (c) 2004, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.readwritesplitting;

import org.postgresql.PGProperty;
import org.postgresql.util.HostSpec;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * Proxy connection that implements read-write splitting by routing SQL statements
 * to master or replica servers based on SQL type and transaction state.
 * <p>
 * This connection delays physical connection establishment until SQL execution time,
 * allowing dynamic routing based on the actual SQL being executed.
 * </p>
 */
public class ReadWriteSplittingConnection implements Connection {

  private final PgConnectionManager connectionManager;
  private final SqlRouteEngine routeEngine;
  private final Properties info;

  // Connection state
  private boolean closed = false;
  private boolean autoCommit = true;
  private String targetServerType;

  /**
   * Creates a new read-write splitting connection.
   *
   * @param hostSpecs array of host specifications
   * @param info connection properties
   * @param url JDBC URL
   * @throws SQLException if initialization fails
   */
  public ReadWriteSplittingConnection(HostSpec[] hostSpecs, Properties info, String url) throws SQLException {
    this.info = info;
    this.connectionManager = new PgConnectionManager(hostSpecs, info, url);
    this.routeEngine = new SqlRouteEngine();
    this.targetServerType = PGProperty.TARGET_SERVER_TYPE.get(info);

    // Initialize auto-commit from properties
    String autoCommitProp = info.getProperty("autoCommit");
    if (autoCommitProp != null) {
      this.autoCommit = Boolean.parseBoolean(autoCommitProp);
    }
  }

  /**
   * Gets the target server type hint.
   *
   * @return the target server type (master/secondary/null)
   */
  public String getTargetServerType() {
    return targetServerType;
  }

  // Statement creation methods (return wrappers)
  @Override
  public Statement createStatement() throws SQLException {
    checkClosed();
    return new ReadWriteSplittingStatement(connectionManager, routeEngine, this);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
    checkClosed();
    // For simplicity, ignore result set type and concurrency
    return createStatement();
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    checkClosed();
    return createStatement();
  }

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    checkClosed();
    return new ReadWriteSplittingPreparedStatement(connectionManager, routeEngine, this, sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
    checkClosed();
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    checkClosed();
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    checkClosed();
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    checkClosed();
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    checkClosed();
    return prepareStatement(sql);
  }

  @Override
  public CallableStatement prepareCall(String sql) throws SQLException {
    checkClosed();
    // CallableStatement always goes to master
    return connectionManager.getMasterConnection().prepareCall(sql);
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().prepareCall(sql, resultSetType, resultSetConcurrency);
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
  }

  // Transaction control methods
  @Override
  public void setAutoCommit(boolean autoCommit) throws SQLException {
    checkClosed();
    this.autoCommit = autoCommit;

    // Record state change for all connections
    connectionManager.recordStateChange(recorder -> recorder.recordSetAutoCommit(autoCommit));

    // Apply to current connection if exists
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setAutoCommit(autoCommit);
    }
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    checkClosed();
    return autoCommit;
  }

  @Override
  public void commit() throws SQLException {
    checkClosed();
    // Commit on master connection
    Connection master = connectionManager.getMasterConnection();
    master.commit();
  }

  @Override
  public void rollback() throws SQLException {
    checkClosed();
    // Rollback on master connection
    Connection master = connectionManager.getMasterConnection();
    master.rollback();
  }

  @Override
  public void rollback(Savepoint savepoint) throws SQLException {
    checkClosed();
    Connection master = connectionManager.getMasterConnection();
    master.rollback(savepoint);
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    checkClosed();
    Connection master = connectionManager.getMasterConnection();
    return master.setSavepoint();
  }

  @Override
  public Savepoint setSavepoint(String name) throws SQLException {
    checkClosed();
    Connection master = connectionManager.getMasterConnection();
    return master.setSavepoint(name);
  }

  @Override
  public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    checkClosed();
    Connection master = connectionManager.getMasterConnection();
    master.releaseSavepoint(savepoint);
  }

  // Connection state methods
  @Override
  public void setTransactionIsolation(int level) throws SQLException {
    checkClosed();
    connectionManager.recordStateChange(recorder -> recorder.recordSetTransactionIsolation(level));

    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setTransactionIsolation(level);
    }
  }

  @Override
  public int getTransactionIsolation() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getTransactionIsolation();
    }
    return Connection.TRANSACTION_READ_COMMITTED;
  }

  @Override
  public void setReadOnly(boolean readOnly) throws SQLException {
    checkClosed();
    connectionManager.recordStateChange(recorder -> recorder.recordSetReadOnly(readOnly));

    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setReadOnly(readOnly);
    }
  }

  @Override
  public boolean isReadOnly() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.isReadOnly();
    }
    return false;
  }

  @Override
  public void setCatalog(String catalog) throws SQLException {
    checkClosed();
    connectionManager.recordStateChange(recorder -> recorder.recordSetCatalog(catalog));

    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setCatalog(catalog);
    }
  }

  @Override
  public String getCatalog() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getCatalog();
    }
    return null;
  }

  @Override
  public void setSchema(String schema) throws SQLException {
    checkClosed();
    connectionManager.recordStateChange(recorder -> recorder.recordSetSchema(schema));

    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setSchema(schema);
    }
  }

  @Override
  public String getSchema() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getSchema();
    }
    return null;
  }

  @Override
  public void setHoldability(int holdability) throws SQLException {
    checkClosed();
    connectionManager.recordStateChange(recorder -> recorder.recordSetHoldability(holdability));

    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setHoldability(holdability);
    }
  }

  @Override
  public int getHoldability() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getHoldability();
    }
    return ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  @Override
  public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    checkClosed();
    connectionManager.recordStateChange(recorder -> recorder.recordSetNetworkTimeout(executor, milliseconds));

    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.setNetworkTimeout(executor, milliseconds);
    }
  }

  @Override
  public int getNetworkTimeout() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getNetworkTimeout();
    }
    return 0;
  }

  @Override
  public void setClientInfo(String name, String value) throws SQLClientInfoException {
    try {
      checkClosed();
      connectionManager.recordStateChange(recorder -> recorder.recordSetClientInfo(name, value));

      Connection current = connectionManager.getCurrentConnection();
      if (current != null && !current.isClosed()) {
        current.setClientInfo(name, value);
      }
    } catch (SQLException e) {
      throw new SQLClientInfoException(e.getMessage(), null);
    }
  }

  @Override
  public void setClientInfo(Properties properties) throws SQLClientInfoException {
    try {
      checkClosed();
      Connection current = connectionManager.getCurrentConnection();
      if (current != null && !current.isClosed()) {
        current.setClientInfo(properties);
      }
    } catch (SQLException e) {
      throw new SQLClientInfoException(e.getMessage(), null);
    }
  }

  @Override
  public String getClientInfo(String name) throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getClientInfo(name);
    }
    return null;
  }

  @Override
  public Properties getClientInfo() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getClientInfo();
    }
    return new Properties();
  }

  // Metadata and type map methods (delegate to master)
  @Override
  public DatabaseMetaData getMetaData() throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().getMetaData();
  }

  @Override
  public Map<String, Class<?>> getTypeMap() throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().getTypeMap();
  }

  @Override
  public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    checkClosed();
    connectionManager.getMasterConnection().setTypeMap(map);
  }

  // Object creation methods (delegate to master)
  @Override
  public String nativeSQL(String sql) throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().nativeSQL(sql);
  }

  @Override
  public Clob createClob() throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().createClob();
  }

  @Override
  public Blob createBlob() throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().createBlob();
  }

  @Override
  public NClob createNClob() throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().createNClob();
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().createSQLXML();
  }

  @Override
  public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().createArrayOf(typeName, elements);
  }

  @Override
  public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
    checkClosed();
    return connectionManager.getMasterConnection().createStruct(typeName, attributes);
  }

  // Warning methods
  @Override
  public SQLWarning getWarnings() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      return current.getWarnings();
    }
    return null;
  }

  @Override
  public void clearWarnings() throws SQLException {
    checkClosed();
    Connection current = connectionManager.getCurrentConnection();
    if (current != null && !current.isClosed()) {
      current.clearWarnings();
    }
  }

  // Connection lifecycle methods
  @Override
  public void close() throws SQLException {
    if (!closed) {
      closed = true;
      connectionManager.close();
    }
  }

  @Override
  public boolean isClosed() throws SQLException {
    return closed;
  }

  @Override
  public boolean isValid(int timeout) throws SQLException {
    if (closed) {
      return false;
    }
    return connectionManager.isValid(timeout);
  }

  @Override
  public void abort(Executor executor) throws SQLException {
    if (!closed) {
      closed = true;
      connectionManager.close();
    }
  }

  // Wrapper methods
  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isAssignableFrom(getClass())) {
      return iface.cast(this);
    }
    Connection current = connectionManager.getCurrentConnection();
    if (current != null) {
      return current.unwrap(iface);
    }
    throw new SQLException("Cannot unwrap to " + iface.getName());
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    if (iface.isAssignableFrom(getClass())) {
      return true;
    }
    Connection current = connectionManager.getCurrentConnection();
    return current != null && current.isWrapperFor(iface);
  }

  /**
   * Checks if the connection is closed and throws an exception if it is.
   *
   * @throws SQLException if the connection is closed
   */
  private void checkClosed() throws SQLException {
    if (closed) {
      throw new SQLException("Connection is closed");
    }
  }
}
